### PR TITLE
added passage overlap feature and few other tweaks, tested on Python 3.6

### PR DESCRIPTION
**Pull request by buchs**

### CODE REVIEW

**Comment by TomFaulkner** [comment]
Thanks for the PR!

I saw some commented out code and some lines that are well over 80 characters. Would you care to clean that up a bit? I tend to follow PEP8 with the line lengths and style. (Though, I don't remember if this library is following it, as I didn't write most of it.)

The new feature looks good, and I appreciate the readme fix, and unit tests.

It would be nice to also have the `__contains__` magic method implemented and perhaps have the `includes` method make use of it. I also saw the private method you added uses dunder, but PEP8 would call for a single underscore prefixing it.

`__contains__` is documented in 3.3.7 here.
https://docs.python.org/3/reference/datamodel.html

How did you come across this repo, are you using the library? I haven't had any feedback on this, so I am curious as to how you found it. Thanks!

**Comment by buchs** [comment]
Hey Tom,

The code was pretty far from PEP8-compliant. I used Pylint and Flake8 to
fix up the code (all, not just the lines I added). The items that remain
are from Pylint:

[image: pylint.png]

And from Flake8:

$ flake8
./tests/test_bible.py:113:1: E302 expected 2 blank lines, found 1
./bible/__init__.py:2:1: F403 'from bible.bible import *' used; unable to
detect undefined names
./bible/__init__.py:4:1: F405 'bible' may be undefined, or defined from
star imports: bible.bible
./bible/bible.py:70:13: E722 do not use bare 'except'
./bible/bible.py:74:17: E722 do not use bare 'except'
./bible/bible.py:81:17: E722 do not use bare 'except'
./bible/bible.py:90:17: E722 do not use bare 'except'
./bible/bible.py:107:17: E722 do not use bare 'except'
./bible/bible.py:123:9: E722 do not use bare 'except'
./bible/bible.py:144:13: E722 do not use bare 'except'
./bible/bible.py:146:9: E722 do not use bare 'except'
./bible/bible.py:188:9: E722 do not use bare 'except'
./bible/bible.py:592:9: E722 do not use bare 'except'


I equivalenced __contains__ to the includes method. This works in an "if"
context (not "for" or "with"). I had the most difficult time trying to get
unittest to recognize a not-in condition and had to invert logic. I did,
there, leave one code line in comments.

Kevin

**Comment by TomFaulkner** [comment]
Thanks, Kevin. I'll take a look. I knew about the bare excepts, I have an issue out if I ever get around to it, to find out why those are there and do them properly.

**Comment by buchs** [comment]
Tom,

Yes, I guess it is just a matter of researching the specific exceptions
that can be raised by the code block.

Kevin

**Comment by TomFaulkner** [comment]
Merged. Thanks, Kevin.

**Pull request merged**
